services:
  app-service:
    build:
      context: ./app-service # specify directory where local Dockerfile is located
    ports:
    - "8000:8000"

  auth-service:
    build:
      context: ./auth-service # specify directory where local Dockerfile is located
    ports:
      - "3000:3000"

  webserver:
    restart: no
    entrypoint: ["echo", "Service webserver disabled"]

  certbot:
    entrypoint: ["echo", "Service certbot disabled"]
